@echo off
cd %~dp0
echo Building TypeScript files...
call npm run build
echo Stopping any existing Node.js processes...
taskkill /F /IM node.exe 2>nul

echo Running direct API test...
node build/direct-test.js
echo.
echo Test completed. Press any key to exit...
pause > nul 