@echo off
echo Testing MCP server with MCP Inspector...
echo Building TypeScript files...
call npm run build

echo Starting server with MCP Inspector in a separate window...
start powershell -Command "npx @modelcontextprotocol/inspector node build/server.js"

echo Waiting for server to start...
timeout /t 5

echo Opening PowerShell to test with curl (leave this window open)...
start powershell -NoExit -Command "echo 'Server is running in a separate window. Test commands:'; echo ''; echo 'curl.exe -X POST http://localhost:3000/jsonrpc -H \"Content-Type: application/json\" -d ''{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"mcp.listTools\",\"params\":{}}'''; echo ''; echo 'curl.exe -X POST http://localhost:3000/jsonrpc -H \"Content-Type: application/json\" -d ''{\"jsonrpc\":\"2.0\",\"id\":\"2\",\"method\":\"auth\",\"params\":{}}'''; echo ''; echo 'curl.exe -X POST http://localhost:3000/jsonrpc -H \"Content-Type: application/json\" -d ''{\"jsonrpc\":\"2.0\",\"id\":\"3\",\"method\":\"schedule_post\",\"params\":{\"message\":\"Test post\"}}'''; echo '';"

echo You can also open the MCP Inspector at http://localhost:5173 